name: Release Workflow

on:
  push:
    branches: [development-1.0]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: write
  packages: write
  security-events: write

jobs:
  release:
    uses: tataranovich/ai-dial-ci/.github/workflows/node_release.yml@main
    with:
      promote: false
      node-version: 24
      maximize-build-space: true
      draft-stable-releases: true
      publish-enabled: false
      ort-enabled: false
      style-checks-enabled: false
      code-checks-enabled: false
    secrets: inherit
