name: Release Workflow

on:
  push:
    branches: [development-old, release-0.*]
  workflow_dispatch:
    inputs:
      promote:
        type: boolean
        default: false
        description: Promote release to stable (for release-0.* branches only)

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: write
  packages: write
  security-events: write

jobs:
  release:
    uses: tataranovich/ai-dial-ci/.github/workflows/node_release.yml@main
    with:
      promote: ${{ github.event_name == 'workflow_dispatch' && inputs.promote }}
      node-version: 24
      maximize-build-space: false
      draft-stable-releases: false
      filter-version: '0\.[0-9]+'
      primary-branch-pattern: '^development-old$'
      release-branch-pattern: '^release-0\.[0-9]+$'
      docker-development-tag: 'development-old'
      # Disable long running parts
      docker-build-enabled: false
      publish-enabled: false
      ort-enabled: false
      style-checks-enabled: false
      code-checks-enabled: false
    secrets: inherit
